language: go

go:
  - 1.7.4

services:
  - postgresql

env:
  - DEX_POSTGRES_DATABASE=postgres DEX_POSTGRES_USER=postgres DEX_POSTGRES_HOST="localhost"


install:
  - go get -u github.com/golang/lint/golint

script:
  - make testall

notifications:
  email: false
